version: "3"
services:
  db:
    image: 'postgres:latest'
    network_mode: bridge
    container_name: categorization
    volumes:
      - postgres-data:/var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - 8001:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=categorization
    restart: unless-stopped
volumes:
  postgres-data: